Errors on multiple sequence + lowercase of the naming authority strings
andrewyatz/hts-specs pull request #2
Opened 2022-03-29 23:10 UTC by tcezard

2022-04-26 16:24 UTC, yash-puligundla commented
In line 563, should "refSeq" be "refseq" if we are going with lower case? 
[Identifiers.org](https://registry.identifiers.org/registry/refseq) also seems to have "refseq" (all lower case)

2022-06-21 11:27 UTC, andrewyatz requested changes
Can we double check that the use of refget in the identifiers was right or did we mean `refseq`

2022-06-21 11:27 UTC, andrewyatz commented on refget.md
> +An array of strings listing the type identifiers supported. Values used should be the same as the one supported by [identifiers.org](https://registry.identifiers.org/registry) such as <code>insdc</co
Should `refget` here actually be `refseq`?

2022-06-21 14:32 UTC, andrewyatz approved these changes

2022-06-21 14:32 UTC, merged